### ISSUE TITLE
Paginated data

### ISSUE THREAD

**Issue by NutanNiraula** [Stefan-UIT/Surveys#19]
@Stefan-UIT Hi, it seems you have not yet implemented pagination in the surveys app. Could you please check the api, it should be able to provide multiple pages of data.

**Comment by Stefan-UIT** [comment]
hi @NutanNiraula , I have implemented the paginations for the surveys app, please help to double check again. I'm really sorry cause I did not notice that there was a pagination feature for the app.
Thanks!
