### ISSUE TITLE
Some discussions on your design choices

### ISSUE THREAD

**Issue by NutanNiraula** [Stefan-UIT/Surveys#20]
@Stefan-UIT Hi, I would love to know your insight and opinions on few points I noticed in your codebase. Please feel free to provide additional context or reasoning behind your ideas.

1. I saw that you were making call to the api directly for unit tests. Could you please provide some insight why you chose to do it that way?

2. I noticed you were printing to standard output in your project, do you think there could be better debug/logging method? 

3. What do you think about code linters like swiftLint?

4. You created your own image caching solution which is interesting. What do you think would be pros and cons of that?

**Comment by Stefan-UIT** [comment]
hi @NutanNiraula , sorry for the late reply, because I have some personal issues to deal with. Here is my answers:

1. Although we usually use fake input from Stub and create Mock objects to test if data update correctly (ex: SurveysModelTests.swift, UserLoginTests.swift...), this was used at very first state of the app’s development, just to make sure we get the correct response like the sample data in the challenge. Anyway, you can ignore that part for now, it can be considered unnecessary test cases.

2. That was fast fingers in development. Yes, we do have better debug/logging tools, the most popular is “os_log”, which provided by Apple. It allows us to log with categories and specify the types (log levels) of logging message. Then later we can filter them in Console. By default, they are: “default”, “info”, “debug”, “error” and “fault” type.

3. I heard of SwiftLint a few times, it is a tool to enforce Swift styles and conventions. Honestly, I did not have a chance to work with it, but I think It will be nice to have it during development step. It might take time at the beginning, but the source code will be easier to maintain and more consistency.

4. Pros and cons: NSCache holds the item in memory and is used for optimal performance, fast access. But it takes up memory (RAM), if we use NSCache, we will responsible for the memory warnings and purge. When memory gets tight it'll start releasing some of its contents. And when the app terminates, the NSCache is lost. 
I assume only few data in the surveys.json, that’s the reason why I chose NSCache for an app demo. In the large project, I usually use “SDWebImage”, which already contain an asynchronous memory + disk image caching with automatic cache expiration handling, support background image decompression to avoid frame rate drop. It was heavily used and has been stress tested.

I will upgrade the source code follows these 4 recommendations, hope that I can send you a new version to review later today.

**Comment by Stefan-UIT** [comment]
Hi @NutanNiraula , I have upgraded the source code follow the recommendations. There are:
- 1 24616f147a51b8342832b444bbf36197617e6628 - [Unit Test] remove unnecessary test cases.
- 2 40929c3843fa59591ef25316b01152b2eb324e5a - [Logging] use os_log to record information about application’s runtime behavior.
- 4 02af46e302fcc88e5b7fcc7464ae080b40cd70b0 - Implemented SDWebImage to load images with asynchronous memory + disk image caching.

All included in pull request #22 , please help to review those first then, I will update you on the 3. SwiftLint very soon.

p/s: I've been busy these days, so the implementation was quite late, just let you know, hope you can understand the situation.

**Comment by NutanNiraula** [comment]
@Stefan-UIT Hi, thank you so much for the fixes on the issue. 🎉  I will try to summarize my review here. I want you to be a part of the discussion. This is a two way process so, feel free to discuss your ideas and raise concerns. I will start with the issues that you have fixed and raise couple of more. The goal is not to ask you to fix them but to start a conversation to better understand your thought process.

[Unit test and error handling]
1. Your test coverage is pretty good and your error handling is good as well, you have used custom error type, throwing functions and multiple catch clauses which was impressive. 👍 

[Logging]
2. Your use of os_log is good but for security concerns it is important to have a separate log layer to make sure the critical information of users are not leaked out to production log, it is always better to remove the debug logs unless it is for some critical paths and also we can use `#file, #function, #line, #dsohandle` to get more information to catch the problems.

[Pagination]
3. Although you have implemented the pagination but the loading UI is blocking the user from swiping up until the paginated request is completed. But this is super nitpicky from my side. Please consider this as a suggestion.

[Network Layer]
4. As with your network layer however it is very simple and hard to scale, you have not abstracted out interceptor layer to handle retries and adapting headers. These are important design decision for later scaling to provide solid oauth implementation, force logout, force upgrade, ssl pinning, adding custom retriers and such. Also, the tokens that we get should be stored in keychain for better security.

[Localization, Colors and assets]
5. We should extract localized strings and color, which is very important for internationalization as well as theming. It would be super great to see pdf vector images but you have tried to strike nice balance with 2x assets.

[Coding and styling]
6. I saw that you have commented code in several places which we can remove. We can remove get from the computed properties, we could remove return but that's a personal choice I think. Also, you have marked final and private in some classes which is very good. Your folder structure and code arrangement is good as well. ✌️ 

Please do not take this as an exhaustive list, these are just things that I noticed on a quick look, I have tried to touch UI, coding style, api design, attention to detail etc to start a conversation. Overall you have nice coding style but there are things that are more desirable as well. I understand your situation, I am not expecting a PR so, please try to sum up your opinions about these things, the goal like I said is to understand your thought process, coding decisions and gitflow practices.

**Comment by Stefan-UIT** [comment]
hi @NutanNiraula , I got your views 👍 , now I knew what I was missing. The thing is when I was first started 🔧 , I thought the challenge was only to focus on building a custom vertical page control (which is simple ⚡ ), so I did not pay too much effort on other things. Let me upgrade the project a little bit 💡, and I will update you fairly soon 🚀 🚀 .

**Comment by Stefan-UIT** [comment]
Hi @NutanNiraula, 
1. First, thanks for the compliment 😉.
 
2. Yep, I agree with you 👍, it is always better to remove the debug logs, but sometimes it saves us lots of time while debugging. I believe there is a reason that this "unified logging" is recommended by Apple. Btw, about leaking out sensitive information, os_log has been supported with private log. For ex: the log "Successfully fetched with token: **%{private}@**". When debugger is no longer attached, the token will be log as **< private >** instead, which prevents from being readable by anyone inside the logs.
 
3. 7c6fe0a7c69d590a3d3c6a3d83a442a2626344c9 - [Surveys] Added footer loading indicator to avoid blocking UI when load more data.
Thank you for very good suggestion 👍. To prevent block UI, I usually add a footer loading indicator.
 
4. 08b10f9e93b60e298396164d604bddc13d9f37db - [Moya] implemented network abstraction layer that sufficiently encapsulates and is entirely type-safe.
👍 Totally agree with you , yes, we should alway have an abstracted network layer in an app. I frequently use Moya as a network abstraction layer that sufficiently encapsulates and entirely type-safe 😉 . If you have a look at the folder "Services", you will notice that the "APIServices.swift" has been deleted, I created NetworkManager instead. Let me explain a bit how's it works: 
       - A NetworkManager contains a provider which will be the main object that we will use to interact with any network service.
       - A Service (UserService, SurveyService...) which defines an entire service, such as: endpoints, params, method, headers..etc. We're using enum, case by case, entirely type-safe 🎉.
       =>  To summarize: Provider -> Service(UserService, SurveyService..) -> Endpoint -> make Request.

5. 09d2919d5f9ac119d9de7c3a06b023b51ac2417f - extract AppColor
👍 Agree that it will be great to see pdf vector images. It is a convenient way to build the image assets at multi resolutions without manually creating each file, so we don't worry about retina artwork or whatever Apple comes up with in the future. But there are no attached assets in the challenge, so I need temporary cheating with some ugly icons. I will look for generating pdf vectors and update you on this very soon 🚀 .
 
6. 1ba6a470e8f75f0928da04e6a12c073ae0cbaeb7 - [SwiftLint] implemented SwiftLint and resolved all warnings to match the styles and conventions.
 
All the commits above are included in pull request #23 . Please help me to review the upgraded source code, and do not hesitate to open more and more issues if needed 🙏.  Don't worry, I do not take this as an exhaustive list, cause I would love to do cool things too 😊. 

Thank you for your advice, I'm really appreciated.

**Comment by Stefan-UIT** [comment]
hi @NutanNiraula ,
Additional revision:
- 2709a949cafe1633b7615686d98cf1120e5c9432 - [Assets] update Assets using pdf vector images with single scale
I found some *.svg icons and converted it to pdf, then updated the assets. The UI looks great 🙏, you can check it out at the latest source code.

Have a nice weekend 😊.

**Comment by NutanNiraula** [comment]
@Stefan-UIT Hi, I received news that the team has decided not to move with your application, the criteria for senior positions is really strict because they are expected to lead a small team and are capable to handle large application end to end. It was really nice reviewing you code and getting to know you. I hope our paths cross again. I suggest you to give your very best for every work you do and wish you all the very best for your future. 🍀

**Comment by Stefan-UIT** [comment]
Thank you, @NutanNiraula .
